name: Lastest commit release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependency
        run: |
          sudo apt-get -y install capnproto

      - name: Set up adoptJDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build trime
        run: ./gradlew assembleDebug
