name: Last commit release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
          sudo add-apt-repository 'deb http://deb.debian.org/debian experimental main'
          sudo apt -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true update
          sudo apt-get -o APT::Get::AllowUnauthenticated=true -y install opencc inkscape capnproto

      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up adoptJDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Trime
        run: make debug
