name: Pull request ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
          sudo add-apt-repository 'deb http://deb.debian.org/debian experimental main'
          sudo apt update
          sudo apt-get -t experimental -y install capnproto=0.8.0-1

      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      
      - name: Setup adopt JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Spotless code style check
        run: make spotless

      - name: Build Trime
        run: make debug
